# Generated by Django 4.2.13 on 2025-02-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
            ],
        ),
    ]
