# Generated by Django 4.2.13 on 2025-02-01 19:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile/wbm-logo.png', null=True, upload_to='profile'),
        ),
    ]
